-- MySQL Script generated by MySQL Workbench
-- Fri Feb 22 11:20:15 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer_mst` (
  `customerid` INT(10) NOT NULL,
  `first_name` VARCHAR(20) NULL,
  `last_name` VARCHAR(20) NULL,
  `birthdate` DATE NULL,
  `gender` VARCHAR(10) NULL,
  `phone_number` VARCHAR(15) NULL,
  `email` VARCHAR(45) NULL,
  `create_time` datetime NOT NULL DEFAULT NOW(),
  `update_time` datetime NULL,
  PRIMARY KEY (`customerid`),
  UNIQUE INDEX `customerid_UNIQUE` (`customerid` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Member_mst` (
  `memberid` INT(10) NOT NULL,
  `Customer_customerid` INT(10) NOT NULL,
  `member_type` INT(5),
  `expired_date` DATE NULL,
  `create_time` datetime NOT NULL DEFAULT NOW(),
  `update_time` datetime NULL,
  UNIQUE INDEX `memberid_UNIQUE` (`memberid` ASC),
  PRIMARY KEY (`memberid`),
  FOREIGN KEY (`Customer_customerid`)
  REFERENCES `mydb`.`Customer_mst` (`customerid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Personal Activity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Personal Activity_txn` (
  `start_time` DATETIME NOT NULL,
  `Member_memberid` INT(10) NOT NULL,
  `end_time` DATETIME NULL,
  `height` FLOAT NULL,
  `weight` FLOAT NULL,
  `create_time` datetime NOT NULL DEFAULT NOW(),
  `update_time` datetime NULL,
  PRIMARY KEY (`start_time`, `Member_memberid`),
  FOREIGN KEY (`Member_memberid`)
  REFERENCES `mydb`.`Member_mst` (`memberid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee_mst` (
  `employeeid` INT(10) NOT NULL,
  `first_name` VARCHAR(20) NULL,
  `last_name` VARCHAR(20) NULL,
  `gender` VARCHAR(10) NULL,
  `salary` FLOAT NULL,
  `date_hired` DATE NULL,
  `employee_type` VARCHAR(20) NULL,
  `supervisor_id` INT(10) NULL,
  `create_time` datetime NOT NULL DEFAULT NOW(),
  `update_time` datetime NULL,
  PRIMARY KEY (`employeeid`),
  FOREIGN KEY (`supervisor_id`)
  REFERENCES `mydb`.`Employee_mst` (`employeeid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Salesperson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Salesperson_mst` (
  `salesid` INT(10) NOT NULL AUTO_INCREMENT,
  `Employee_employeeid` INT(10) NOT NULL,
  `commision_rate` FLOAT NULL,
  `create_time` datetime NOT NULL DEFAULT NOW(),
  `update_time` datetime NULL,
  PRIMARY KEY (`salesid`),
  FOREIGN KEY (`Employee_employeeid`)
  REFERENCES `mydb`.`Employee_mst` (`employeeid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Trainer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Trainer_mst` (
  `trainerid` INT(10) NOT NULL AUTO_INCREMENT,
  `Employee_employeeid` INT(10) NOT NULL,
  `certification` VARCHAR(20) NULL,
  `experience` INT(2) NULL,
  `charge_rate` FLOAT NULL,
  `create_time` datetime NOT NULL DEFAULT NOW(),
  `update_time` datetime NULL,
  PRIMARY KEY (`trainerid`),
  FOREIGN KEY (`Employee_employeeid`)
  REFERENCES `mydb`.`Employee_mst` (`employeeid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Class_mst` (
  `classid` INT(10) NOT NULL AUTO_INCREMENT,
  `Trainer_trainerid` INT(10) NOT NULL,
  `class_name` VARCHAR(45) NULL,
  `start_time` TIME NULL,
  `end_time` TIME NULL,
  `level` INT(1) NULL,
  `charge_rate` FLOAT NULL,
  `create_time` datetime NOT NULL DEFAULT NOW(),
  `update_time` datetime NULL,
  PRIMARY KEY (`classid`),
  FOREIGN KEY (`Trainer_trainerid`)
  REFERENCES `mydb`.`Trainer_mst` (`trainerid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Class_Training_Schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Class_Training_Schedule_txn` (
  `schedule_id` INT(10) NOT NULL AUTO_INCREMENT,
  `Member_memberid` INT(10) NOT NULL,
  `Class_classid` INT(10) NOT NULL,
  `rating` INT(1) NULL,
  `create_time` datetime NOT NULL DEFAULT NOW(),
  `update_time` datetime NULL,
  PRIMARY KEY (`schedule_id`),
  FOREIGN KEY (`Member_memberid`)
  REFERENCES `mydb`.`Member_mst` (`memberid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  FOREIGN KEY (`Class_classid`)
  REFERENCES `mydb`.`Class_mst` (`classid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Initial Fee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Initial Fee_txn` (
  `Customer_customerid` INT(10) NOT NULL,
  `Salesperson_salesid` INT(10) NOT NULL,
  `created_date` DATE NULL,
  `payment_method` VARCHAR(25) NULL,
  `payment_amount` FLOAT NULL,
  `create_time` datetime NOT NULL DEFAULT NOW(),
  `update_time` datetime NULL,
  PRIMARY KEY (`Customer_customerid`, `Salesperson_salesid`),
  FOREIGN KEY (`Customer_customerid`)
  REFERENCES `mydb`.`Customer_mst` (`customerid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  FOREIGN KEY (`Salesperson_salesid`)
  REFERENCES `mydb`.`Salesperson_mst` (`salesid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Renewal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Renewal_txn` (
  `renewal_id` INT(10) NOT NULL  AUTO_INCREMENT,
  `Member_memberid` INT(10) NOT NULL,
  `Employee_employeeid` INT(10) NULL,
  `created_date` DATE NULL,
  `payment_method` VARCHAR(25) NULL,
  `payment_amount` FLOAT NULL,
  `create_time` datetime NOT NULL DEFAULT NOW(),
  `update_time` datetime NULL,
  PRIMARY KEY (`renewal_id`),
  FOREIGN KEY (`Member_memberid`)
  REFERENCES `mydb`.`Member_mst` (`memberid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  FOREIGN KEY (`Employee_employeeid`)
  REFERENCES `mydb`.`Employee_mst` (`employeeid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Personal_Training_Schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Personal_Training_Schedule_txn` (
  `schedule_id` INT(10) NOT NULL AUTO_INCREMENT,
  `Member_memberid` INT(10) NOT NULL,
  `Trainer_trainerid` INT(10) NOT NULL,
  `start_time` DATETIME NULL,
  `end_time` DATETIME NULL,
  `rating` INT(1) NULL,
  `create_time` datetime NOT NULL DEFAULT NOW(),
  `update_time` datetime NULL,
  PRIMARY KEY (`schedule_id`),
  FOREIGN KEY (`Member_memberid`)
  REFERENCES `mydb`.`Member_mst` (`memberid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  FOREIGN KEY (`Trainer_trainerid`)
  REFERENCES `mydb`.`Trainer_mst` (`trainerid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view2` (`id` INT);

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view1`;
USE `mydb`;

-- -----------------------------------------------------
-- View `mydb`.`view2`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view2`;
USE `mydb`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
